- name: Clone a repo 
  hosts: localhost 
  become: yes 
  tasks:
    - name: Create a directory 
      file:
        path: /tmp/ansible 
        state: directory 

    - name: Clone repo 
      git:
        repo:  https://github.com/devopstrainings/ansible.git
        dest: /tmp/ansible 